### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by Mike-Honey** [neuml/kernelpipes#3]
Hi David.  I'm very excited to try this project - thanks for posting it.

I'm trying to install it on a Windows VM I'm using for the CORD-19 project, but the "pip install ." is failing. I'm running python 3.8.2 embedded.

Any ideas?

```
D:\Users\mikeh\Documents\kernelpipes>pip install .
Processing d:\users\mikeh\documents\kernelpipes
    ERROR: Command errored out with exit status 1:
     command: 'd:\users\mikeh\documents\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Users\\mikeh\\AppData\\Local\\Temp\\1\\pip-req-build-p_2nikk5\\setup.py'"'"'; __file__='"'"'D:\\Users\\mikeh\\AppData\\Local\\Temp\\1\\pip-req-build-p_2nikk5\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'D:\Users\mikeh\AppData\Local\Temp\1\pip-pip-egg-info-bg1dwtem'
         cwd: D:\Users\mikeh\AppData\Local\Temp\1\pip-req-build-p_2nikk5\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Users\mikeh\AppData\Local\Temp\1\pip-req-build-p_2nikk5\setup.py", line 20, in <module>
        packages=find_packages(where="src/python/"),
      File "d:\users\mikeh\documents\python\lib\site-packages\setuptools\__init__.py", line 70, in find
        convert_path(where),
      File "distutils\util.py", line 124, in convert_path
    ValueError: path 'src/python/' cannot end with '/'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by davidmezzetti** [comment]
Great Mike! Glad you're giving it a try. I just made a change to the install script that removes the trailing slash, based on what I saw it seems like Windows doesn't consider that a valid path. 

Please let me know if that works.

**Comment by Mike-Honey** [comment]
Yes!  It's installed now.  

Quite late here now but I'll have a play in the morning.

**Comment by davidmezzetti** [comment]
Sounds good, glad it works now. Let me know if you run into other issues or if you have ideas for additional steps to add.
