### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2e38'

### ISSUE THREAD

**Issue by Mike-Honey** [neuml/kernelpipes#4]
It triggered, but failed - looks like an issue with a Unicode character. Perhaps I'm missing a requirement?

Same python env - 3.8.2, Windows embedded 64-bit.

```
2020-06-07 17:00:01,690 [INFO] kernel    : Running Kernel: mikehoney/ai-powered-literature-review-with-submissions
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "D:\Users\mikeh\Documents\python\Scripts\kernelpipes.exe\__main__.py", line 7, in <module>
  File "d:\users\mikeh\documents\python\lib\site-packages\kernelpipes\pipeline.py", line 116, in main
    Pipeline.run(sys.argv[1])
  File "d:\users\mikeh\documents\python\lib\site-packages\kernelpipes\pipeline.py", line 105, in run
    Pipeline.schedule(directory, pipeline)
  File "d:\users\mikeh\documents\python\lib\site-packages\kernelpipes\pipeline.py", line 76, in schedule
    Pipeline.execute(directory, pipeline)
  File "d:\users\mikeh\documents\python\lib\site-packages\kernelpipes\pipeline.py", line 45, in execute
    Kernel(directory, step["kernel"])()
  File "d:\users\mikeh\documents\python\lib\site-packages\kernelpipes\steps\step.py", line 20, in __call__
    return self.run()
  File "d:\users\mikeh\documents\python\lib\site-packages\kernelpipes\steps\kernel.py", line 39, in run
    kaggle.api.kernels_pull(self.kernel, path, True, False)
  File "d:\users\mikeh\documents\python\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 2018, in kernels_pull
    f.write(blob['source'])
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2e38' in position 9963: character maps to <undefined>
```

**Comment by davidmezzetti** [comment]
This looks like it's an issue with how the Kaggle API is writing the ipynb file out when pulling it down. The default locale encoding on Windows is CP-1252 and the notebook your pulling must have  utf-8 characters in it. 

_File "d:\users\mikeh\documents\python\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 2018, in kernels_pull
    f.write(blob['source'])_

As a work around, can you try setting the following Python environment variable, before running kernelpipes to see if that helps at all? It should set all operations to be utf-8 aware.

set PYTHONUTF8=1

**Comment by Mike-Honey** [comment]
Thanks for the tip.  When I re-run it now I get:

```
[INFO] check     : allen-institute-for-ai/CORD-19-research-challenge up-to-date
[INFO] pipeline  : Pipeline complete
```

Is there any way to force it to run?

**Comment by davidmezzetti** [comment]
Great, looks like that worked.

No way to force it via the command line right now. But you can comment out the check line in the yml file by putting a # in front of it and that will force it to run. I would also comment out the schedule line if you have that enabled to force it to run once immediately.

**Comment by Mike-Honey** [comment]
Got it - thanks so much for this project!

**Comment by davidmezzetti** [comment]
Great, glad it's working and helping out.
